name: dbt_one
version: '1.0.0'
config-version: 2

# Nome do perfil usado no profiles.yml
profile: 'dbt_one'

# Diretórios onde os diferentes tipos de arquivos estão localizados
model-paths: ["models"]         # Diretório principal dos modelos
analysis-paths: ["analyses"]    # Diretório para análises
test-paths: ["validacao"]       # Diretório para testes
seed-paths: ["seeds"]           # Diretório para seeds
macro-paths: ["macros"]         # Diretório para macros
snapshot-paths: ["snapshots"]   # Diretório para snapshots

# Diretório de saída
target-path: "target"

# Diretórios a serem limpos pelo comando `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

#VARIAVES
vars:
  filtro_municipio: ""
  filtro_uf: "RJ"

# Configurações dos modelos

models:
  dbt_one:  # Este nome deve corresponder ao nome do projeto
    dbt_cnpj_rfb:   # Nome do subdiretório dentro de "models"
      +materialized: table  # Configuração padrão para os modelos neste subdiretório dbt run --models models/teste
