name: dbt_one
version: '1.0.0'
config-version: 2

# Nome do perfil usado no profiles.yml
profile: 'dbt_one'

# Diretórios onde os diferentes tipos de arquivos estão localizados
model-paths: ["models"]         # Diretório principal dos modelos
analysis-paths: ["analyses"]    # Diretório para análises
test-paths: ["validacao"]       # Diretório para testes
seed-paths: ["seeds"]           # Diretório para seeds
macro-paths: ["macros"]         # Diretório para macros
snapshot-paths: ["snapshots"]   # Diretório para snapshots

# Diretório de saída
target-path: "target"

# Diretórios a serem limpos pelo comando `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Variáveis configuráveis para o projeto
vars:
  filtro_municipio: ""       # Filtro para municípios
  filtro_uf: "RJ"            # Filtro para estados
  codrecp: "1010"            # Código do recp
  municipio_dasn: "5837"       # Código do município para o DASN
  # dataset_name: ""           # Nome do dataset (pode ser alterado via --vars)

# Configurações dos modelos
models:
  dbt_one:                   # Este nome deve corresponder ao nome do projeto
  
    dbt_cnpj_rfb:            # Nome do subdiretório dentro de "models/dbt_cnpj_rfb"
      +materialized: table   # Configuração padrão: os modelos serão materializados como tabelas
      # +schema: "{{ var('dataset_name') }}" # Usa a variável dataset_name com padrão 'dbt_cnpj_rfb'
    
    dbt_dasn:                # Nome do subdiretório dentro de "models/dbt_dasn"
      +materialized: view    # Configuração padrão: os modelos serão materializados como views
      # +schema: "{{ var('dataset_name') }}"     # Usa a variável dataset_name com padrão 'dbt_dasn'